  # Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[Î»](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[Î»](bold red)"


[gcloud]
disabled = true


[kubernetes]
disabled = true

[kubernetes.context_aliases]

"*minikube*" = "minikube"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"


[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_range = "07:00:00-18:00:00"
