[character]
success_symbol = "[Î»](bold green)"
error_symbol = "[Î»](bold red)"

[gcloud]
disabled = true

[nodejs]
disabled = true

[kubernetes]
disabled = true

[kubernetes.context_aliases]
"*minikube*" = "minikube"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_range = "08:00:00-16:00:00"
